### ISSUE TITLE
SCP-807

### ISSUE THREAD

**Issue by Palkiabraz** [Drake62610/Astro-Bot#31]
SCP-807 est un programme par mes soins qui permet de rajouter des défis pour "SCP : Secret Laboratory".
J'ai plein de fonctionnalités en tête, mais je ne suis pas très bon pour coder. J'en appelle à vous !

Choses à faire : 
- Ajouter des défis (~ 15 par classe)
- Optimiser le code (Les différentes appellations de classe, meilleure visualisation du code...)
- Ajouter des images en rapport avec le défi en question
- Intégration de Rich Discord dans le bot pour qu'il envoie les défis en MP au lieu du channel général.

**Comment by Drake62610** [comment]
Voici quelque pistes :  
[] Le code est largement optimisable, utilise la puissance des listes de python pour faire tes verification, voici un exemple : 
```python
list_Dboi = ['DBOI','D-Boi',ClasseD','Classe_D']

test = DBOI

if test in list_Dboi:
     print('Hello')
else:
     print('Hallo')
```
Le code va print Hello.

[] Pour les images pense à les heberger quelque par (imgur, etc) car la capacite de stockage du serveur existe mais ne devrait pas être utilisé pour ça.

[] Il est possible d'envoyer un mesage privé en utilisant la commande : 
```python
     await self.bot.send_message(await self.bot.start_private_message(ctx.message.author), "yo bitch")
```

Ici l'objet ctx est indispensable pour connaitre l'identité de la personne qui passe la commande, il suffit de l'ajouter dans la commande comme ceci
```python
@commands.command(pass_context=True)
    async def myfunction(ctx):
          #Dostuff
```
