### ISSUE TITLE
J'ai tiré un servant 0 nat nommé notfound

### ISSUE THREAD

**Issue by Drake62610** [Drake62610/Astro-Bot#7]
![image](https://user-images.githubusercontent.com/27460666/41003462-1f1f42d8-6917-11e8-9154-bd03ce18c38f.png)

**Comment by jonathanlaffut** [comment]
Ce problème survient quand aucune correspondance entre la base de données et les données en dur dans le programme n'est trouvée.

Ce problème peut toujours survenir, mais un print "NOT FOUND: [nom]" a été ajouté pour mieux détecter les données qui causent ce problème.
Si ce problème survient, il faut regarder le nom qui a été print et modifier ce nom dans fgoroll.Gacha.raw_init pour qu'il corresponde à celui qui se trouve dans la base de donnée qui correspond.

Lorsque l'on corrige un nom de Servant, il faut vérifier qu'aucun autre Servant ne porte le même nom. Sinon, il faut alors remplacer les noms concernés par des dictionnaires contenant nom et sclass du Servant.
